const {
  createNewUser,
  checkUserByEmail,
  getUserOrdersQuery,
  getUserOrdersReqQuery,
  getUserData,
  getUserNotificationsQueries,
  addUserNotification,
} = require('./user');
const {
  createNewProvider,
  updateProvider,
  getProviderDataById,
} = require('./provider');

const {
  deleteOrderReq,
  addOrderRequest,
  isAlreadyHeired,
  getAcceptedOrders,
  updateStateOrderRequest,
  postOrder,
  getPendingOrderRequest,
  getOrderReqByOrderIdQuery,
  updateOrderStatePauseQuery,
  updateOrderStateStartQuery,
  updateStateQuery,
  updateOrderDurationQuery,
  updateOrderBillQuery,
  updateOrderResourceQuery,
  getOrder,
} = require('./order');

module.exports = {
  createNewUser,
  checkUserByEmail,
  createNewProvider,
  postOrder,
  updateStateOrderRequest,
  getPendingOrderRequest,
  deleteOrderReq,
  addOrderRequest,
  getUserOrdersQuery,
  getUserOrdersReqQuery,
  getAcceptedOrders,
  updateProvider,
  getProviderDataById,
  isAlreadyHeired,
  updateOrderStatePauseQuery,
  getOrderReqByOrderIdQuery,
  getUserData,
  getUserNotificationsQueries,
  addUserNotification,
  updateOrderStateStartQuery,
  updateStateQuery,
  updateOrderDurationQuery,
  updateOrderBillQuery,
  updateOrderResourceQuery,
  getOrder,
};
